// src/questions.js

export const rounds = [
  {
    round: 1,
    name: "Round 1",
    questions: [
      {
        id: 1,
        text: "Which of the following is NOT a characteristic of object-oriented programming?",
        options: ["Inheritance", "Encapsulation", "Polymorphism", "Compilation"],
        correctAnswer: "Compilation",
      },
      {
        id: 2,
        text: "What does the 'NaN' value in a dataset represent?",
        options: ["0", "Not a Number", "A number", "Null and Negative"],
        correctAnswer: "Not a Number",
      },
      {
        id: 3,
        text: "What does a high bias in a model usually cause?",
        options: ["Underfitting", "Overfitting", "High variance", "None"],
        correctAnswer: "Underfitting",
      },
      {
        id: 4,
        text: "Which of these sorting algorithms is the fastest on average?",
        options: ["Bubble Sort", "Merge Sort", "Selection Sort", "Insertion Sort"],
        correctAnswer: "Merge Sort",
      },
      {
        id: 5,
        text: "What is the capital of Canada?",
        options: ["Toronto", "Ottawa", "Vancouver", "Montreal"],
        correctAnswer: "Ottawa",
      },
      {
        id: 6,
        text: "Which of the following is a key stage in the data science process?",
        options: ["Data colouring", "Data linking", "Data cleaning", "Data forwarding"],
        correctAnswer: "Data cleaning",
      },
      {
        id: 7,
        text: "Which of the following is used for containerization?",
        options: ["Docker", "Git", "Jenkins", "Ansible"],
        correctAnswer: "Docker",
      },
      {
        id: 8,
        text: "What kind of problem does a Support Vector Machine (SVM) solve?",
        options: [
          "Clustering",
          "Dimensionality reduction",
          "Classification and regression",
          "Association rule mining",
        ],
        correctAnswer: "Classification and regression",
      },
      {
        id: 9,
        text: "Explain how Naïve Bayes handles categorical vs continuous features.",
        options: [
          "Ignores categorical features",
          "Uses frequency for categorical; assumes Gaussian for continuous",
          "Uses frequency for continuous",
          "Uses Gaussian for all features",
        ],
        correctAnswer: "Uses frequency for categorical; assumes Gaussian for continuous",
      },
      {
        id: 10,
        text: "Which of the following is a lightweight data-interchange format?",
        options: ["XML", "JSON", "CSV", "TXT"],
        correctAnswer: "JSON",
      },
      {
        id: 11,
        text: "What is the purpose of a firewall?",
        options: [
          "To store data securely",
          "To monitor and control incoming and outgoing network traffic",
          "To increase CPU speed",
          "To back up data",
        ],
        correctAnswer: "To monitor and control incoming and outgoing network traffic",
      },
      {
        id: 12,
        text: "The first program that runs when a computer starts is stored in:",
        options: ["RAM", "BIOS/UEFI", "Cache", "Hard disk"],
        correctAnswer: "BIOS/UEFI",
      },
      {
        id: 13,
        text: "Which of the following is a high-level programming language?",
        options: ["Assembly", "Python", "Machine Code", "Binary"],
        correctAnswer: "Python",
      },
      {
        id: 14,
        text: "What is the time complexity of binary search in a sorted array?",
        options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        correctAnswer: "O(log n)",
      },
      {
        id: 15,
        text: "How does DBSCAN determine cluster boundaries?",
        options: [
          "Density-based: groups points with many close neighbours",
          "By minimizing within-cluster variance",
          "Random partitioning",
          "By maximizing between-cluster variance",
        ],
        correctAnswer: "Density-based: groups points with many close neighbours",
      },
      {
        id: 16,
        text: "Who holds the record for the most Olympic gold medals?",
        options: ["Usain Bolt", "Michael Phelps", "Larisa Latynina", "Mark Spitz"],
        correctAnswer: "Michael Phelps",
      },
      {
        id: 17,
        text: "Which metric is commonly used for regression evaluation?",
        options: ["Accuracy", "Precision", "Mean Squared Error", "F1 Score"],
        correctAnswer: "Mean Squared Error",
      },
      {
        id: 18,
        text: "In statistics, what is the mean?",
        options: ["The middle value", "The most frequent value", "The average", "The square root"],
        correctAnswer: "The average",
      },
      {
        id: 19,
        text: "What is the purpose of a confusion matrix?",
        options: [
          "Displays correct and incorrect predictions across classes",
          "Measures training time",
          "Tracks model hyperparameters",
          "Stores dataset metadata",
        ],
        correctAnswer: "Displays correct and incorrect predictions across classes",
      },
      {
        id: 20,
        text: "What does the term 'overfitting' refer to?",
        options: [
          "A model that performs poorly on training data",
          "A model that performs well on test data",
          "A model that memorizes training data but performs poorly on new data",
          "A model with low variance",
        ],
        correctAnswer: "A model that memorizes training data but performs poorly on new data",
      },
      {
        id: 21,
        text: "Who is known as the Father of Computer Science?",
        options: ["Charles Babbage", "Alan Turing", "John von Neumann", "Blaise Pascal"],
        correctAnswer: "Alan Turing",
      },
      {
        id: 22,
        text: "Who is known as the Father of Artificial Intelligence?",
        options: ["Marvin Minsky", "John McCarthy", "Alan Turing", "Geoffrey Hinton"],
        correctAnswer: "John McCarthy",
      },
      {
        id: 23,
        text: "Which of these is a common loss function for regression problems?",
        options: [
          "Categorical cross-entropy",
          "Binary cross-entropy",
          "Mean squared error",
          "Hinge loss",
        ],
        correctAnswer: "Mean squared error",
      },
      {
        id: 24,
        text: "Who is known as the father of Artificial Intelligence?",
        options: ["Alan Turing", "John McCarthy", "Marvin Minsky", "Geoffrey Hinton"],
        correctAnswer: "John McCarthy",
      },
      {
        id: 25,
        text: "What does standard deviation measure?",
        options: ["Central tendency", "Spread of data", "Categorical relationships", "Skewness"],
        correctAnswer: "Spread of data",
      },
      {
        id: 26,
        text: "Which data structure uses LIFO principle?",
        options: ["Queue", "Stack", "Array", "Linked List"],
        correctAnswer: "Stack",
      },
      {
        id: 27,
        text: "What does ‘outlier’ mean in data analysis?",
        options: [
          "Missing value",
          "A duplicate value",
          "A data point significantly different from others",
          "A central value",
        ],
        correctAnswer: "A data point significantly different from others",
      },
      {
        id: 28,
        text: "What does skewness measure?",
        options: ["Correlation", "Symmetry of data distribution", "Variance", "Frequency"],
        correctAnswer: "Symmetry of data distribution",
      },
      {
        id: 29,
        text: "How does random forest improve upon a single decision tree?",
        options: [
          "Averages multiple trees to reduce variance",
          "Uses deeper trees to reduce bias",
          "Chooses optimal features only",
          "Uses a single strong learner",
        ],
        correctAnswer: "Averages multiple trees to reduce variance",
      },
      {
        id: 30,
        text: "Which one is used to uniquely identify a network interface on the internet?",
        options: ["MAC Address", "IP Address", "URL", "Port Number"],
        correctAnswer: "IP Address",
      },
      {
        id: 31,
        text: "Which is the largest island in the world?",
        options: ["Greenland", "New Guinea", "Borneo", "Madagascar"],
        correctAnswer: "Greenland",
      },
      {
        id: 32,
        text: "Which of these is a distributed version control system?",
        options: ["SVN", "Git", "CVS", "RCS"],
        correctAnswer: "Git",
      },
      {
        id: 33,
        text: "Which AI field focuses on enabling computers to understand images and videos?",
        options: ["NLP", "Robotics", "Computer Vision", "Deep Learning"],
        correctAnswer: "Computer Vision",
      },
      {
        id: 34,
        text: "Which of the following is NOT a type of cloud service?",
        options: ["SaaS", "PaaS", "IaaS", "DaaS"],
        correctAnswer: "DaaS",
      },
      {
        id: 35,
        text: "Which of these is a type of categorical variable?",
        options: ["Height", "Temperature", "Country", "Age"],
        correctAnswer: "Country",
      },
      {
        id: 36,
        text: "Which city is known as the “City of Canals”?",
        options: ["Venice", "Amsterdam", "Bangkok", "Bruges"],
        correctAnswer: "Venice",
      },
      {
        id: 37,
        text: "Which type of machine learning problem is K-Means used for?",
        options: [
          "Supervised Classification",
          "Supervised Regression",
          "Unsupervised Clustering",
          "Reinforcement Learning",
        ],
        correctAnswer: "Unsupervised Clustering",
      },
      {
        id: 38,
        text: "What is the maximum value storable in an unsigned 8-bit integer?",
        options: ["127", "255", "512", "1023"],
        correctAnswer: "255",
      },
      {
        id: 39,
        text: "In NLP, what does stemming do?",
        options: [
          "Removes all stop words",
          "Converts text to numbers",
          "Reduces words to their root form",
          "Finds sentiment",
        ],
        correctAnswer: "Reduces words to their root form",
      },
      {
        id: 40,
        text: "Which of the following protocols is used for secure communication over the web?",
        options: ["FTP", "HTTP", "HTTPS (TLS/SSL)", "SMTP"],
        correctAnswer: "HTTPS (TLS/SSL)",
      },
      {
        id: 41,
        text: "Which game did IBM’s Deep Blue famously beat a world champion in?",
        options: ["Poker", "Go", "Chess", "Checkers"],
        correctAnswer: "Chess",
      },
      {
        id: 42,
        text: "What does the role of describe() in Pandas?",
        options: [
          "Visualize data",
          "Train a model",
          "Summarize statistics of numerical columns",
          "Remove nulls",
        ],
        correctAnswer: "Summarize statistics of numerical columns",
      },
      {
        id: 43,
        text: "Which of the following is NOT a primary key constraint in databases?",
        options: ["Unique", "Not Null", "Foreign Key", "Auto Increment"],
        correctAnswer: "Foreign Key",
      },
      {
        id: 44,
        text: "In a classification task, precision is defined as:",
        options: ["TP / (TP + FN)", "TP / (TP + FP)", "TP / (FP + FN)", "(TP + TN) / (TP + FP + TN+ FN)"],
        correctAnswer: "TP / (TP + FP)",
      },
      {
        id: 45,
        text: "Which of these is used to reduce dimensionality?",
        options: ["Decision Trees", "PCA", "RNN", "MLP"],
        correctAnswer: "PCA",
      },
      {
        id: 46,
        text: "Which of these is an example of a relational database?",
        options: ["MongoDB", "Oracle", "Redis", "Cassandra"],
        correctAnswer: "Oracle",
      },
      {
        id: 47,
        text: "Which of the following is NOT a relational database operation?",
        options: ["JOIN", "SELECT", "INSERT", "LOOP"],
        correctAnswer: "LOOP",
      },
      {
        id: 48,
        text: "Which of the following is a symmetric encryption algorithm?",
        options: ["RSA", "AES", "DSA", "ECC"],
        correctAnswer: "AES",
      },
      {
        id: 49,
        text: "Who developed the theory of relativity?",
        options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
        correctAnswer: "Albert Einstein",
      },
      {
        id: 50,
        text: "Who is called the Father of the Internet?",
        options: ["Tim Berners-Lee", "Vint Cerf & Robert Kahn", "Larry Page & Sergey Brin", "Ray Tomlinson"],
        correctAnswer: "Vint Cerf & Robert Kahn",
      },
      {
        id: 51,
        text: "What is the purpose of train-test split?",
        options: ["Improve training speed", "Prevent overfitting", "Evaluate model performance", "Increase accuracy"],
        correctAnswer: "Evaluate model performance",
      },
      {
        id: 52,
        text: "Which of the following is a markup language?",
        options: ["HTML", "Python", "C++", "Java"],
        correctAnswer: "HTML",
      },
      {
        id: 53,
        text: "Who was the first female Prime Minister of India?",
        options: ["Sarojini Naidu", "Indira Gandhi", "Pratibha Patil", "Sonia Gandhi"],
        correctAnswer: "Indira Gandhi",
      },
      {
        id: 54,
        text: "What is the role of groupby() in Pandas?",
        options: ["Merge datasets", "Plot graphs", "Aggregate data based on a key", "Sort columns"],
        correctAnswer: "Aggregate data based on a key",
      },
      {
        id: 55,
        text: "What is the purpose of the cost function in machine learning?",
        options: [
          "To decrease accuracy",
          "To increase bias",
          "To measure the error of predictions",
          "To track input features",
        ],
        correctAnswer: "To measure the error of predictions",
      },
      {
        id: 56,
        text: "In computer networks, what does LAN stand for?",
        options: ["Local Area Network", "Large Area Network", "Local Access Node", "Linked Area Network"],
        correctAnswer: "Local Area Network",
      },
      {
        id: 57,
        text: "What is a confusion matrix used for?",
        options: ["Regression models", "Classification accuracy", "Clustering", "Data cleaning"],
        correctAnswer: "Classification accuracy",
      },
      {
        id: 58,
        text: "Which of these is NOT a type of software testing?",
        options: ["Unit Testing", "Integration Testing", "Link Testing", "System Testing"],
        correctAnswer: "Link Testing",
      },
      {
        id: 59,
        text: "Prolog is mainly used in:",
        options: ["AI & Expert Systems", "Game Development", "System Programming", "Database Management"],
        correctAnswer: "AI & Expert Systems",
      },
      {
        id: 60,
        text: "Which of the following is used to schedule jobs in Unix/Linux?",
        options: ["Cron", "Jenkins", "Git", "Docker"],
        correctAnswer: "Cron",
      },
      {
        id: 61,
        text: "What does the output of a sigmoid activation function?",
        options: ["0 or 1", "0 to 1", "-1 to 1", "-∞ to +∞"],
        correctAnswer: "0 to 1",
      },
      {
        id: 62,
        text: "Which of the following is an unsupervised learning algorithm?",
        options: ["Decision Tree", "Naive Bayes", "K-Means", "Linear Regression"],
        correctAnswer: "K-Means",
      },
      {
        id: 63,
        text: "What does AI stand for?",
        options: [
          "Automatic Integration",
          "Artificial Intelligence",
          "Augmented Information",
          "Applied Inference",
        ],
        correctAnswer: "Artificial Intelligence",
      },
      {
        id: 64,
        text: "The smallest unit of data in memory is:",
        options: ["Byte", "Bit", "Nibble", "Word"],
        correctAnswer: "Bit",
      },
      {
        id: 65,
        text: "What does gradient descent help with?",
        options: ["Model evaluation", "Data normalization", "Minimizing loss", "Increasing accuracy directly"],
        correctAnswer: "Minimizing loss",
      },
      {
        id: 66,
        text: "Difference between classification and regression problems?",
        options: [
          "Both predict continuous variables",
          "Both predict categories",
          "Classification predicts categories; regression predicts numeric values",
          "Classification predicts numbers; regression predicts categories",
        ],
        correctAnswer: "Classification predicts categories; regression predicts numeric values",
      },
      {
        id: 67,
        text: "Which type of plot helps to visualize correlation between two numeric variables?",
        options: ["Pie chart", "Scatter plot", "Bar chart", "Heatmap"],
        correctAnswer: "Scatter plot",
      },
      {
        id: 68,
        text: "Which chart is best suited for showing categorical data distribution?",
        options: ["Line chart", "Pie chart", "Histogram", "Scatter plot"],
        correctAnswer: "Pie chart",
      },
      {
        id: 69,
        text: "What does SSL stand for?",
        options: ["Secure Sockets Layer", "Safe System Layer", "Simple Security Link", "Standard Socket Link"],
        correctAnswer: "Secure Sockets Layer",
      },
      {
        id: 70,
        text: "Which Python library is used for data visualization?",
        options: ["Keras", "Matplotlib", "NLTK", "NumPy"],
        correctAnswer: "Matplotlib",
      },
      {
        id: 71,
        text: "What does TF-IDF stand for in NLP?",
        options: [
          "Term Factor–Inverse Document Factor",
          "Term Frequency–Inverse Document Frequency",
          "Term Function–Index Data Filter",
          "Token Frequency–ID Filter",
        ],
        correctAnswer: "Term Frequency–Inverse Document Frequency",
      },
      {
        id: 72,
        text: "Which of the following is used to prevent SQL injection attacks?",
        options: ["Parameterized queries", "Hard coding", "Encryption", "Indexing"],
        correctAnswer: "Parameterized queries",
      },
      {
        id: 73,
        text: "What does cross-validation used for?",
        options: ["Training speed", "Model tuning and evaluation", "Normalization", "Removing missing values"],
        correctAnswer: "Model tuning and evaluation",
      },
      {
        id: 74,
        text: "Which company developed the C# language?",
        options: ["Oracle", "IBM", "Microsoft", "Google"],
        correctAnswer: "Microsoft",
      },
      {
        id: 75,
        text: "Which of the following is used for version control?",
        options: ["Git", "Docker", "Jenkins", "Kubernetes"],
        correctAnswer: "Git",
      },
      {
        id: 76,
        text: "In classification, recall is defined as:",
        options: ["TP / (TP + FN)", "TP / (TP + FP)", "TP / (TN + FP)", "TN / (TN + FP)"],
        correctAnswer: "TP / (TP + FN)",
      },
      {
        id: 77,
        text: "Which device is used to measure atmospheric pressure?",
        options: ["Thermometer", "Barometer", "Hygrometer", "Altimeter"],
        correctAnswer: "Barometer",
      },
      {
        id: 78,
        text: "Which of the following is a functional programming language?",
        options: ["C++", "Haskell", "Java", "Python"],
        correctAnswer: "Haskell",
      },
      {
        id: 79,
        text: "The control unit in CPU is responsible for:",
        options: ["Performing calculations", "Storing data", "Directing data flow", "Printing results"],
        correctAnswer: "Directing data flow",
      },
      {
        id: 80,
        text: "Virtual memory is implemented using:",
        options: ["Cache memory", "Hard disk", "GPU", "BIOS"],
        correctAnswer: "Hard disk",
      },
      {
        id: 81,
        text: "What is the purpose of DNS?",
        options: [
          "To translate domain names into IP addresses",
          "To store web pages",
          "To secure websites",
          "To route emails",
        ],
        correctAnswer: "To translate domain names into IP addresses",
      },
      {
        id: 82,
        text: "What is the primary goal of Artificial Intelligence?",
        options: [
          "To replicate human intelligence",
          "To build hardware",
          "To manage databases",
          "To create websites",
        ],
        correctAnswer: "To replicate human intelligence",
      },
      {
        id: 83,
        text: "What is data normalization?",
        options: [
          "Removing duplicates",
          "Removing outliers",
          "Scaling features to a standard range",
          "Adding more data",
        ],
        correctAnswer: "Scaling features to a standard range",
      },
      {
        id: 84,
        text: "In which country is the city of Machu Picchu located?",
        options: ["Mexico", "Peru", "Chile", "Bolivia"],
        correctAnswer: "Peru",
      },
      {
        id: 85,
        text: "What is the range of the correlation coefficient?",
        options: ["0 to 1", "-1 to 0", "-1 to 1", "-2 to 2"],
        correctAnswer: "-1 to 1",
      },
      {
        id: 86,
        text: "Which of the following is a Python library used for data manipulation?",
        options: ["TensorFlow", "Pandas", "OpenCV", "Flask"],
        correctAnswer: "Pandas",
      },
      {
        id: 87,
        text: "What is a perceptron?",
        options: ["A deep learning model", "A single-layer neural network", "An optimization function", "A loss metric"],
        correctAnswer: "A single-layer neural network",
      },
      {
        id: 88,
        text: "Which AI technique is used in recommendation systems?",
        options: ["K-Means", "Regression Trees", "Collaborative Filtering", "Reinforcement Learning"],
        correctAnswer: "Collaborative Filtering",
      },
      {
        id: 89,
        text: "Which bus is fastest in a computer?",
        options: ["Data bus", "Address bus", "Control bus", "Cache bus"],
        correctAnswer: "Cache bus",
      },
      {
        id: 90,
        text: "Which activation function is commonly used in hidden layers of deep neural networks?",
        options: ["Softmax", "Sigmoid", "ReLU", "Tanh"],
        correctAnswer: "ReLU",
      },
      {
        id: 91,
        text: "Which company developed the AI model 'GPT'?",
        options: ["OpenAI", "IBM", "Microsoft", "Google"],
        correctAnswer: "OpenAI",
      },
      {
        id: 92,
        text: "Which model uses a policy and reward system?",
        options: ["Supervised model", "Unsupervised model", "Reinforcement Learning", "SVM"],
        correctAnswer: "Reinforcement Learning",
      },
      {
        id: 93,
        text: "What is epoch in neural networks?",
        options: ["Size of input", "Batch of layers", "One full pass of training data", "Model accuracy"],
        correctAnswer: "One full pass of training data",
      },
      {
        id: 94,
        text: "FORTRAN stands for:",
        options: ["Formula Translation", "Format Transfer", "Forward Translation", "Formula Transfer"],
        correctAnswer: "Formula Translation",
      },
      {
        id: 95,
        text: "Which function is best suited for binary classification?",
        options: ["Linear", "Softmax", "Sigmoid", "ReLU"],
        correctAnswer: "Sigmoid",
      },
      {
        id: 96,
        text: "Which of the following is an example of an interpreted language?",
        options: ["Java", "C++", "Python", "C"],
        correctAnswer: "Python",
      },
      {
        id: 97,
        text: "Which of the following is NOT a Python data type?",
        options: ["List", "Tuple", "ArrayList", "Dictionary"],
        correctAnswer: "ArrayList",
      },
      {
        id: 98,
        text: "What does AUC-ROC stand for?",
        options: [
          "Accuracy Under Conditions – Rate of Classification",
          "Area Under Curve – Receiver Operating Characteristic",
          "Area Under Cutoff – ROC",
          "Accuracy Usage Curve – ROC",
        ],
        correctAnswer: "Area Under Curve – Receiver Operating Characteristic",
      },
      {
        id: 99,
        text: "Which of the following is used to connect multiple network devices in a LAN?",
        options: ["Switch", "Router", "Modem", "Repeater"],
        correctAnswer: "Switch",
      },
      {
        id: 100,
        text: "What is backpropagation used for in neural networks?",
        options: ["Data preprocessing", "Model evaluation", "Updating weights", "Feature extraction"],
        correctAnswer: "Updating weights",
      },
      {
        id: 101,
        text: "Which of the following is a NoSQL database?",
        options: ["MySQL", "MongoDB", "Oracle", "SQL Server"],
        correctAnswer: "MongoDB",
      },
      {
        id: 102,
        text: "What does the default axis for row-wise operations in Pandas?",
        options: ["axis = 1", "axis = 'row'", "axis = 0", "axis = None"],
        correctAnswer: "axis = 0",
      },
      {
        id: 103,
        text: "Which continent is the Sahara Desert located on?",
        options: ["Asia", "Africa", "Australia", "North America"],
        correctAnswer: "Africa",
      },
      {
        id: 104,
        text: "Describe the k-means clustering algorithm.",
        options: [
          "Iteratively assigns points to nearest centroid and updates centroids",
          "Groups data by hierarchical splits only",
          "Assigns points randomly with no updates",
          "Uses density estimation for clusters",
        ],
        correctAnswer: "Iteratively assigns points to nearest centroid and updates centroids",
      },
      {
        id: 105,
        text: "Which method is used to handle missing data?",
        options: ["Drop columns", "Impute with mean/median", "Forward fill", "All of the above"],
        correctAnswer: "All of the above",
      },
      {
        id: 106,
        text: "Which of the following is NOT a type of neural network?",
        options: ["CNN", "RNN", "GAN", "SVM"],
        correctAnswer: "SVM",
      },
      {
        id: 107,
        text: "What is a confusion matrix?",
        options: ["A graph", "A table for evaluating classification results", "A regression tool", "An unsupervised learning model"],
        correctAnswer: "A table for evaluating classification results",
      },
      {
        id: 108,
        text: "What does PCA stand for?",
        options: [
          "Primary Component Analysis",
          "Partial Component Adjustment",
          "Principal Component Analysis",
          "Predictive Clustering Algorithm",
        ],
        correctAnswer: "Principal Component Analysis",
      },
      {
        id: 109,
        text: "Which metric is used for evaluating classification problems?",
        options: ["MSE", "RMSE", "Accuracy", "R-squared"],
        correctAnswer: "Accuracy",
      },
      {
        id: 110,
        text: "What type of galaxy is the Milky Way?",
        options: ["Elliptical", "Spiral", "Irregular", "Lenticular"],
        correctAnswer: "Spiral",
      },
      {
        id: 111,
        text: "Compare PCA and t-SNE for dimensionality reduction.",
        options: [
          "PCA is slower but preserves local structure",
          "t-SNE is linear and preserves variance",
          "Both are nonlinear methods",
          "PCA is linear; t-SNE is nonlinear and better for visualization",
        ],
        correctAnswer: "PCA is linear; t-SNE is nonlinear and better for visualization",
      },
      {
        id: 112,
        text: "Which of the following is used to prevent overfitting in deep learning?",
        options: ["More layers", "Dropout", "Larger datasets", "Data scaling"],
        correctAnswer: "Dropout",
      },
      {
        id: 113,
        text: "What does .iloc[] do in Pandas?",
        options: ["Select columns by label", "Select rows/columns by index", "Plot data", "Rename columns"],
        correctAnswer: "Select rows/columns by index",
      },
      {
        id: 114,
        text: "Who invented the email system?",
        options: ["Ray Tomlinson", "Vint Cerf", "Tim Berners-Lee", "John McCarthy"],
        correctAnswer: "Ray Tomlinson",
      },
      {
        id: 115,
        text: "Which of the following is a linear data structure?",
        options: ["Tree", "Graph", "Linked List", "Hash Table"],
        correctAnswer: "Linked List",
      },
      {
        id: 116,
        text: "What is the worst-case time complexity of quicksort?",
        options: ["O(n)", "O(n log n)", "O(log n)", "O(n²)"],
        correctAnswer: "O(n²)",
      },
      {
        id: 117,
        text: "Which of the following is an example of a interpreted language?",
        options: ["Java", "C++", "Python", "C"],
        correctAnswer: "Python",
      },
      {
        id: 118,
        text: "What is the goal of feature scaling?",
        options: [
          "To delete irrelevant features",
          "To convert features into labels",
          "To bring all features to the same range",
          "To increase model complexity",
        ],
        correctAnswer: "To bring all features to the same range",
      },
      {
        id: 119,
        text: "Which AI application allows computers to understand and generate human language?",
        options: ["Computer Vision", "Natural Language Processing", "Robotics", "Cryptography"],
        correctAnswer: "Natural Language Processing",
      },
      {
        id: 120,
        text: "Which of these is a NoSQL database type?",
        options: ["Key-Value", "Columnar", "Document", "All of the above"],
        correctAnswer: "All of the above",
      },
      {
        id: 121,
        text: "What does the kernel trick in SVMs?",
        options: [
          "Converts nonlinear data into higher dimensions for linear separation",
          "Reduces overfitting by penalizing large weights",
          "Finds nearest neighbours in original space",
          "Speeds up training by pruning features",
        ],
        correctAnswer: "Converts nonlinear data into higher dimensions for linear separation",
      },
      {
        id: 122,
        text: "Which programming language is used in statistical computing?",
        options: ["R", "C++", "SQL", "Ruby"],
        correctAnswer: "R",
      },
      {
        id: 123,
        text: "Why is DNS required for the internet?",
        options: [
          "To encrypt data",
          "To map human-readable names to IP addresses",
          "To prevent hacking",
          "To provide faster routing",
        ],
        correctAnswer: "To map human-readable names to IP addresses",
      },
      {
        id: 124,
        text: "Which layer of OSI model provides end-to-end communication?",
        options: ["Network", "Transport", "Data Link", "Physical"],
        correctAnswer: "Transport",
      },
      {
        id: 125,
        text: "What does NLP stand for in AI?",
        options: [
          "Natural Language Processing",
          "Neural Logic Programming",
          "Network Learning Procedure",
          "Numeric Linear Prediction",
        ],
        correctAnswer: "Natural Language Processing",
      },
      {
        id: 126,
        text: "Which term describes the ability of a machine to improve its performance over time from experience?",
        options: ["Hard coding", "Machine Learning", "Static programming", "Manual operation"],
        correctAnswer: "Machine Learning",
      },
      {
        id: 127,
        text: "Which model architecture powers GPT, BERT, and other large language models?",
        options: ["RNN", "CNN", "Transformer", "LSTM"],
        correctAnswer: "Transformer",
      },
      {
        id: 128,
        text: "Which of the following is a virtual machine software?",
        options: ["VMware", "Docker", "Git", "Jenkins"],
        correctAnswer: "VMware",
      },
      {
        id: 129,
        text: "How is precision different from recall?",
        options: [
          "Both = TP/(TP+FN)",
          "Precision = TP/(TP+FN); Recall = TP/(TP+FP)",
          "Both = TP/(TP+FP)",
          "Precision = TP/(TP+FP); Recall = TP/(TP+FN)",
        ],
        correctAnswer: "Precision = TP/(TP+FP); Recall = TP/(TP+FN)",
      },
      {
        id: 130,
        text: "What is the range of the tanh activation function?",
        options: ["0 to 1", "-1 to 1", "0 to ∞", "-∞ to ∞"],
        correctAnswer: "-1 to 1",
      },
      {
        id: 131,
        text: "Which of the following is a characteristic of supervised learning?",
        options: ["No labels", "Feedback-based", "Output variable is known", "Self-learning"],
        correctAnswer: "Output variable is known",
      },
      {
        id: 132,
        text: "Which planet has the most moons?",
        options: ["Saturn", "Jupiter", "Neptune", "Uranus"],
        correctAnswer: "Saturn",
      },
      {
        id: 133,
        text: "Which protocol is used to send email?",
        options: ["FTP", "SMTP", "HTTP", "SSH"],
        correctAnswer: "SMTP",
      },
      {
        id: 134,
        text: "What is the default port for HTTP?",
        options: ["80", "443", "21", "22"],
        correctAnswer: "80",
      },
      {
        id: 135,
        text: "Which of the following is used for asynchronous communication in networking?",
        options: ["TCP", "UDP", "IP", "FTP"],
        correctAnswer: "UDP",
      },
      {
        id: 136,
        text: "What is the main goal of Data Science?",
        options: [
          "Building websites",
          "Creating databases",
          "Extracting insights from data",
          "Data entry and storage",
        ],
        correctAnswer: "Extracting insights from data",
      },
      {
        id: 137,
        text: "UNIX operating system was developed in:",
        options: ["1965", "1969", "1972", "1980"],
        correctAnswer: "1969",
      },
      {
        id: 138,
        text: "What is the size of IPv6 address?",
        options: ["32 bits", "64 bits", "128 bits", "256 bits"],
        correctAnswer: "128 bits",
      },
      {
        id: 139,
        text: "Which of these is an advantage of decision trees?",
        options: ["High overfitting", "Difficult to interpret", "Requires normalization", "Easy to interpret"],
        correctAnswer: "Easy to interpret",
      },
      {
        id: 140,
        text: "What kind of AI is designed to perform specific tasks but cannot perform beyond those tasks?",
        options: ["Narrow AI", "General AI", "Super AI", "Strong AI"],
        correctAnswer: "Narrow AI",
      },
      {
        id: 141,
        text: "What is the currency of Japan?",
        options: ["Yen", "Yuan", "Won", "Ringgit"],
        correctAnswer: "Yen",
      },
      {
        id: 142,
        text: "Which model is NOT typically used in regression?",
        options: ["Linear Regression", "Decision Tree", "Naive Bayes", "Random Forest"],
        correctAnswer: "Naive Bayes",
      },
      {
        id: 143,
        text: "Which HTTP status code represents “Not Found”?",
        options: ["200", "301", "404", "500"],
        correctAnswer: "404",
      },
      {
        id: 144,
        text: "Explain decision tree splitting criteria such as Gini index vs entropy.",
        options: [
          "Only Gini measures impurity",
          "Both measure variance; entropy is faster",
          "Only entropy measures impurity",
          "Both measure impurity; Gini is simpler computationally",
        ],
        correctAnswer: "Both measure impurity; Gini is simpler computationally",
      },
      {
        id: 145,
        text: "What does EDA stand for in data science?",
        options: [
          "Expert Data Analysis",
          "Efficient Data Aggregation",
          "Exploratory Data Analysis",
          "Enhanced Data Access",
        ],
        correctAnswer: "Exploratory Data Analysis",
      },
      {
        id: 146,
        text: "Which programming language is commonly used in AI research?",
        options: ["Python", "HTML", "CSS", "SQL"],
        correctAnswer: "Python",
      },
      {
        id: 147,
        text: "Which type of memory is non-volatile and can be electrically erased?",
        options: ["RAM", "ROM", "EEPROM", "Cache"],
        correctAnswer: "EEPROM",
      },
      {
        id: 148,
        text: "What is the purpose of a boxplot?",
        options: [
          "Display time series",
          "Compare frequencies",
          "Show data distribution and outliers",
          "Model predictions",
        ],
        correctAnswer: "Show data distribution and outliers",
      },
      {
        id: 149,
        text: "Mount Everest lies on the border of Nepal and which country?",
        options: ["China", "India", "Bhutan", "Pakistan"],
        correctAnswer: "China",
      },
      {
        id: 150,
        text: "Which ocean is the largest by surface area?",
        options: ["Atlantic", "Pacific", "Indian", "Arctic"],
        correctAnswer: "Pacific",
      },
    ],
  },
  {
    round: 2,
    name: "Round 2",
    questions: [
      {
        id: 1,
        text: "In k-NN, what is the effect of increasing 'k'?",
        options: [
          "Model becomes more complex",
          "Model becomes simpler and less sensitive to noise",
          "Model becomes overfitted",
          "None of the above",
        ],
        correctAnswer: "Model becomes simpler and less sensitive to noise",
      },
      {
        id: 2,
        text: "Which method is used to handle class imbalance in classification problems?",
        options: ["Bagging", "SMOTE", "PCA", "Ridge Regression"],
        correctAnswer: "SMOTE",
      },
      {
        id: 3,
        text: "Which of the following is a non-volatile memory?",
        options: ["RAM", "Cache", "ROM", "Register"],
        correctAnswer: "ROM",
      },
      {
        id: 4,
        text: "What is the primary purpose of an operating system?",
        options: [
          "Run software faster",
          "Provide internet access",
          "Manage hardware and software resources",
          "Compile code",
        ],
        correctAnswer: "Manage hardware and software resources",
      },
      {
        id: 5,
        text: "What is a foreign key in SQL?",
        options: [
          "A unique identifier in a table",
          "A key that points to a primary key in another table",
          "A column used for indexing",
          "A duplicate column in a table",
        ],
        correctAnswer: "A key that points to a primary key in another table",
      },
      {
        id: 6,
        text: "Which animal is known to have the most powerful bite in the animal kingdom?",
        options: ["Lion", "Hippopotamus", "Crocodile", "Great White Shark"],
        correctAnswer: "Crocodile",
      },
      {
        id: 7,
        text: "The “overfitting” problem in machine learning refers to:",
        options: [
          "Model fails to learn patterns",
          "Model learns noise along with patterns",
          "Model has high bias",
          "Model is too simple",
        ],
        correctAnswer: "Model learns noise along with patterns",
      },
      {
        id: 8,
        text: "What is the key difference between static and dynamic memory allocation?",
        options: [
          "Static is faster but limited, dynamic is flexible but slower",
          "Static is used for variables, dynamic is for functions",
          "Dynamic memory is always allocated on the stack",
          "Static memory is cleared automatically",
        ],
        correctAnswer: "Static is faster but limited, dynamic is flexible but slower",
      },
      {
        id: 9,
        text: "In programming, what does IDE stand for?",
        options: [
          "Internal Development Environment",
          "Integrated Development Environment",
          "Internet Design Editor",
          "Integrated Debugging Environment",
        ],
        correctAnswer: "Integrated Development Environment",
      },
      {
        id: 10,
        text: "Which vitamin is primarily obtained from sunlight?",
        options: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin K"],
        correctAnswer: "Vitamin D",
      },
      {
        id: 11,
        text: "Which of the following is not a feature selection technique?",
        options: [
          "Recursive Feature Elimination",
          "Chi-square test",
          "Label Encoding",
          "Mutual Information",
        ],
        correctAnswer: "Label Encoding",
      },
      {
        id: 12,
        text: "Which logical gate returns true only if both inputs are true?",
        options: ["OR", "XOR", "AND", "NAND"],
        correctAnswer: "AND",
      },
      {
        id: 13,
        text: "Who was the first woman in space?",
        options: ["Kalpana Chawla", "Sally Ride", "Valentina Tereshkova", "Mae Jemison"],
        correctAnswer: "Valentina Tereshkova",
      },
      {
        id: 14,
        text: "Which clause is used to filter groups after aggregation?",
        options: ["WHERE", "ORDER BY", "GROUP BY", "HAVING"],
        correctAnswer: "HAVING",
      },
      {
        id: 15,
        text: "What does `iloc[2:5]` return in a pandas Data Frame?",
        options: [
          "Rows with indices 2 to 5",
          "Columns 2 to 5",
          "Rows at positions 2, 3, 4",
          "First 5 rows",
        ],
        correctAnswer: "Rows at positions 2, 3, 4",
      },
      {
        id: 16,
        text: "Which algorithm is commonly used for classification tasks in machine learning?",
        options: ["K-means", "Decision Tree", "Apriori", "PCA"],
        correctAnswer: "Decision Tree",
      },
      {
        id: 17,
        text: "Which JOIN returns all records from the left table and the matched records from the right table?",
        options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        correctAnswer: "LEFT JOIN",
      },
      {
        id: 18,
        text: "Which Python library is best suited for statistical modeling and tests?",
        options: ["NumPy", "pandas", "matplotlib", "statsmodels"],
        correctAnswer: "statsmodels",
      },
      {
        id: 19,
        text: "What does the `axis=1` parameter do in pandas functions like `drop()` or `sum()`?",
        options: [
          "Applies operation row-wise",
          "Applies operation column-wise",
          "Deletes data",
          "Applies the function to both axes",
        ],
        correctAnswer: "Applies operation column-wise",
      },
      {
        id: 20,
        text: "What is the smallest country in the world by area?",
        options: ["Monaco", "Nauru", "Vatican City", "San Marino"],
        correctAnswer: "Vatican City",
      },
      {
        id: 21,
        text: "Who was the U.S. President during the Great Depression and World War II?",
        options: [
          "Herbert Hoover",
          "Harry Truman",
          "Franklin D. Roosevelt",
          "Dwight Eisenhower",
        ],
        correctAnswer: "Franklin D. Roosevelt",
      },
      {
        id: 22,
        text: "What does NLP stand for?",
        options: [
          "Natural Layer Processing",
          "Nonlinear Language Programming",
          "Natural Language Processing",
          "Next Level Processing",
        ],
        correctAnswer: "Natural Language Processing",
      },
      {
        id: 23,
        text: "What is the role of the activation function in a neural network?",
        options: [
          "To sort data",
          "To add non-linearity",
          "To scale inputs",
          "To normalize output",
        ],
        correctAnswer: "To add non-linearity",
      },
      {
        id: 24,
        text: "Which of the following is a supervised learning algorithm?",
        options: ["K-means clustering", "Linear Regression", "Apriori", "PCA"],
        correctAnswer: "Linear Regression",
      },
      {
        id: 25,
        text: "Which river is the longest in the world (by length)?",
        options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
        correctAnswer: "Nile",
      },
      {
        id: 26,
        text: "Which layer of the OSI model handles IP addressing?",
        options: ["Transport", "Data Link", "Network", "Application"],
        correctAnswer: "Network",
      },
      {
        id: 27,
        text: "Which country is known as the “Land of the Rising Sun”?",
        options: ["China", "Thailand", "Japan", "South Korea"],
        correctAnswer: "Japan",
      },
      {
        id: 28,
        text: "In reinforcement learning, the “agent” interacts with:",
        options: ["Only data", "The environment", "The operator", "The database"],
        correctAnswer: "The environment",
      },
      {
        id: 29,
        text: "What does a p-value signify in hypothesis testing?",
        options: [
          "Probability of the alternative hypothesis being true",
          "Likelihood of making a Type II error",
          "Probability of observing the result given the null hypothesis is true",
          "Confidence interval",
        ],
        correctAnswer: "Probability of observing the result given the null hypothesis is true",
      },
      {
        id: 30,
        text: "In an Artificial Neural Network, a hidden layer is:",
        options: [
          "The input layer",
          "The output layer",
          "Any layer between input and output",
          "Dropout layer",
        ],
        correctAnswer: "Any layer between input and output",
      },
      {
        id: 31,
        text: "Which of the following is a valid IP address?",
        options: ["192.168.1.300", "10.0.0.256", "172.16.254.1", "123.456.78.90"],
        correctAnswer: "172.16.254.1",
      },
      {
        id: 32,
        text: "Which of these is a dimensionality reduction technique?",
        options: ["PCA", "Linear Regression", "Decision Tree", "Random Forest"],
        correctAnswer: "PCA",
      },
      {
        id: 33,
        text: "Which gas makes up the majority of the Earth’s atmosphere?",
        options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
        correctAnswer: "Nitrogen",
      },
      {
        id: 34,
        text: "What does `df.isnull().sum()` return in pandas?",
        options: [
          "Count of nulls in the entire Data Frame",
          "True/False for missing values",
          "Count of nulls per column",
          "Count of non-null values",
        ],
        correctAnswer: "Count of nulls per column",
      },
      {
        id: 35,
        text: "Which country has the most natural lakes in the world?",
        options: ["Russia", "Brazil", "Canada", "USA"],
        correctAnswer: "Canada",
      },
      {
        id: 36,
        text: "What symbol is used for comments in Python?",
        options: ["//", "<!-- -->", "#", "/* */"],
        correctAnswer: "#",
      },
      {
        id: 37,
        text: "Who was the first female Prime Minister of the United Kingdom?",
        options: ["Margaret Thatcher", "Theresa May", "Elizabeth II", "Angela Merkel"],
        correctAnswer: "Margaret Thatcher",
      },
      {
        id: 38,
        text: "Which of the following best describes the difference between a compiler and an interpreter?",
        options: [
          "Compiler translates line by line, interpreter all at once",
          "Interpreter translates to binary, compiler does not",
          "Compiler translates the entire code before execution, interpreter translates during execution",
          "They are both the same",
        ],
        correctAnswer: "Compiler translates the entire code before execution, interpreter translates during execution",
      },
      {
        id: 39,
        text: "Which Indian city is known as the “Silicon Valley of India”?",
        options: ["Hyderabad", "Pune", "Gurugram", "Bengaluru"],
        correctAnswer: "Bengaluru",
      },
      {
        id: 40,
        text: "What will `np.nan == np.nan` return?",
        options: ["True", "False", "Error", "None"],
        correctAnswer: "False",
      },
      {
        id: 41,
        text: "Which company developed the C programming language?",
        options: ["Microsoft", "IBM", "Apple", "Bell Labs"],
        correctAnswer: "Bell Labs",
      },
      {
        id: 42,
        text: "What is the main purpose of DNS in networking?",
        options: [
          "To encrypt data in transit",
          "To assign MAC addresses",
          "To map domain names to IP addresses",
          "To configure firewalls",
        ],
        correctAnswer: "To map domain names to IP addresses",
      },
      {
        id: 43,
        text: "Which loss function is often used for binary classification?",
        options: ["Mean Squared Error", "Cross Entropy", "Smooth L1 Loss", "Hinge Loss"],
        correctAnswer: "Cross Entropy",
      },
      {
        id: 44,
        text: "What does “regularization” address in ML models?",
        options: ["Too much training data", "Overfitting", "Underfitting", "Low variance"],
        correctAnswer: "Overfitting",
      },
      {
        id: 45,
        text: "What is the key purpose of dropout in neural networks?",
        options: ["Increase model size", "Prevent overfitting", "Speed up training", "Reduce bias"],
        correctAnswer: "Prevent overfitting",
      },
      {
        id: 46,
        text: "What does the keyword static mean when declaring a variable inside a function in C?",
        options: [
          "The variable is global",
          "The variable can only be used once",
          "The variable retains its value between function calls",
          "The variable cannot be modified",
        ],
        correctAnswer: "The variable retains its value between function calls",
      },
      {
        id: 47,
        text: "Which of the following is a characteristic of overfitting?",
        options: [
          "High bias, low variance",
          "High training accuracy, low test accuracy",
          "Low training accuracy, high test accuracy",
          "All of the above",
        ],
        correctAnswer: "High training accuracy, low test accuracy",
      },
      {
        id: 48,
        text: "What is “transfer learning” in AI?",
        options: [
          "Training separate models for each task",
          "Using knowledge from one task for another",
          "Supervising every step",
          "Testing data only",
        ],
        correctAnswer: "Using knowledge from one task for another",
      },
      {
        id: 49,
        text: "Which country became the first to grant women the right to vote?",
        options: ["United States", "Australia", "New Zealand", "Sweden"],
        correctAnswer: "New Zealand",
      },
      {
        id: 50,
        text: "What is the currency of South Korea?",
        options: ["Yen", "Won", "Yuan", "Ringgit"],
        correctAnswer: "Won",
      },
      {
        id: 51,
        text: "Which company launched AlphaGo, the first AI to beat a world Go champion?",
        options: ["DeepMind", "OpenAI", "IBM", "Microsoft"],
        correctAnswer: "DeepMind",
      },
      {
        id: 52,
        text: "What is the output of the following Boolean expression: !(1 && 0 || 1)?",
        options: ["0", "1", "True", "False"],
        correctAnswer: "0",
      },
      {
        id: 53,
        text: "In SQL, what is the difference between DELETE and TRUNCATE?",
        options: [
          "TRUNCATE can be rolled back, DELETE cannot",
          "DELETE is faster than TRUNCATE",
          "TRUNCATE removes all rows without logging each row",
          "DELETE only works with indexed tables",
        ],
        correctAnswer: "TRUNCATE removes all rows without logging each row",
      },
      {
        id: 54,
        text: "Which SQL statement is used to extract unique values from a column?",
        options: ["SELECT *", "SELECT DISTINCT", "SELECT UNIQUE", "SELECT GROUP"],
        correctAnswer: "SELECT DISTINCT",
      },
      {
        id: 55,
        text: "In binary, what is the result of 1011 + 1101?",
        options: ["11000", "10100", "11110", "10010"],
        correctAnswer: "11110",
      },
      {
        id: 56,
        text: "Which process evaluates a model using unseen data?",
        options: ["Overfitting", "Regularization", "Cross-validation", "Normalization"],
        correctAnswer: "Cross-validation",
      },
      {
        id: 57,
        text: "Which desert is the largest hot desert in the world?",
        options: ["Gobi", "Arabian", "Kalahari", "Sahara"],
        correctAnswer: "Sahara",
      },
      {
        id: 58,
        text: "What’s the function of a “loss function” in model training?",
        options: [
          "Evaluates model performance",
          "Creates more inputs",
          "Stores trained weights",
          "Builds data pipelines",
        ],
        correctAnswer: "Evaluates model performance",
      },
      {
        id: 59,
        text: "A “convolutional layer” is generally found in which type of neural network?",
        options: ["CNN", "RNN", "GAN", "SVM"],
        correctAnswer: "CNN",
      },
      {
        id: 60,
        text: "What does multicollinearity in regression indicate?",
        options: [
          "Target variable is linearly dependent",
          "Independent variables are highly correlated",
          "Errors are dependent",
          "Features are irrelevant",
        ],
        correctAnswer: "Independent variables are highly correlated",
      },
      {
        id: 61,
        text: "Which algorithm is most likely to be affected by outliers?",
        options: ["Random Forest", "K-means", "Gradient Boosting", "Naive Bayes"],
        correctAnswer: "K-means",
      },
      {
        id: 62,
        text: "What does the term “polymorphism” mean in object-oriented programming?",
        options: [
          "Multiple constructors in a class",
          "One function behaving differently based on input types",
          "One class inheriting from multiple classes",
          "Overriding a static method",
        ],
        correctAnswer: "One function behaving differently based on input types",
      },
      {
        id: 63,
        text: "What is the goal of one-hot encoding?",
        options: [
          "Normalize numerical data",
          "Combine categories into a single variable",
          "Convert categorical variables into binary format",
          "Impute missing values",
        ],
        correctAnswer: "Convert categorical variables into binary format",
      },
      {
        id: 64,
        text: "What part of the cell contains the genetic material (DNA)?",
        options: ["Mitochondria", "Ribosome", "Nucleus", "Cytoplasm"],
        correctAnswer: "Nucleus",
      },
      {
        id: 65,
        text: "Which tech company acquired Twitter in 2022?",
        options: ["Google", "Apple", "Elon Musk / X Corp", "Meta"],
        correctAnswer: "Elon Musk / X Corp",
      },
      {
        id: 66,
        text: "Who is the current (2025) Secretary-General of the United Nations?",
        options: ["António Guterres", "Ban Ki-moon", "Kofi Annan", "Amina Mohammed"],
        correctAnswer: "António Guterres",
      },
      {
        id: 67,
        text: "Which of the following is used to uniquely identify a row in a table?",
        options: ["Foreign key", "Index", "Primary key", "Column"],
        correctAnswer: "Primary key",
      },
      {
        id: 68,
        text: "In AI, “feature engineering” refers to:",
        options: [
          "Creating input variables for better model performance",
          "Compressing files",
          "Changing output labels",
          "Generating random noise",
        ],
        correctAnswer: "Creating input variables for better model performance",
      },
      {
        id: 69,
        text: "Which HTTP method is idempotent and used for updating resources?",
        options: ["GET", "POST", "PUT", "PATCH"],
        correctAnswer: "PUT",
      },
      {
        id: 70,
        text: "Which of the following is a compiled language?",
        options: ["Python", "JavaScript", "Java", "PHP"],
        correctAnswer: "Java",
      },
      {
        id: 71,
        text: "The main idea of a Support Vector Machine (SVM) is to:",
        options: [
          "Group data with decision boundaries",
          "Generate new data",
          "Forecast time series",
          "Sort inputs",
        ],
        correctAnswer: "Group data with decision boundaries",
      },
      {
        id: 72,
        text: "Which software development model involves repeating cycles (iterations)?",
        options: ["Waterfall Model", "Spiral Model", "V-Model", "Big Bang Model"],
        correctAnswer: "Spiral Model",
      },
      {
        id: 73,
        text: "Which war was triggered by the invasion of Kuwait in 1990?",
        options: ["Vietnam War", "Iraq War", "Gulf War", "Afghanistan War"],
        correctAnswer: "Gulf War",
      },
      {
        id: 74,
        text: "Which planet rotates on its side relative to its orbit?",
        options: ["Mars", "Neptune", "Uranus", "Venus"],
        correctAnswer: "Uranus",
      },
      {
        id: 75,
        text: "Which technique is used to scale data between 0 and 1?",
        options: ["Standardization", "Normalization", "One-hot encoding", "Binning"],
        correctAnswer: "Normalization",
      },
      {
        id: 76,
        text: "What is the output of `df.info()` in pandas?",
        options: [
          "Descriptive statistics",
          "Column types and non-null counts",
          "Data correlation",
          "Visual representation of data",
        ],
        correctAnswer: "Column types and non-null counts",
      },
      {
        id: 77,
        text: "Ensemble methods in machine learning involve:",
        options: [
          "Combining several models for better accuracy",
          "Using a single tree model",
          "Always using linear regression",
          "Increasing dataset size",
        ],
        correctAnswer: "Combining several models for better accuracy",
      },
      {
        id: 78,
        text: "What is a Generative Adversarial Network (GAN) composed of?",
        options: [
          "Generator and Discriminator",
          "Encoder and Decoder",
          "Feature Selector and Classifier",
          "Input and Output",
        ],
        correctAnswer: "Generator and Discriminator",
      },
      {
        id: 79,
        text: "What type of distribution is used to model the number of times an event occurs in a fixed interval?",
        options: ["Normal", "Binomial", "Poisson", "Exponential"],
        correctAnswer: "Poisson",
      },
      {
        id: 80,
        text: "What is the default port for HTTP?",
        options: ["20", "22", "80", "443"],
        correctAnswer: "80",
      },
      {
        id: 81,
        text: "Which country hosted the 2024 Summer Olympics?",
        options: ["Japan", "USA", "France", "Italy"],
        correctAnswer: "France",
      },
      {
        id: 82,
        text: "What is the purpose of “hyperparameters” in machine learning?",
        options: [
          "Model weights",
          "Settings that control learning process",
          "Features from the data",
          "Output variables",
        ],
        correctAnswer: "Settings that control learning process",
      },
      {
        id: 83,
        text: "Which of the following is used for relational database management?",
        options: ["Python", "MySQL", "HTML", "JSON"],
        correctAnswer: "MySQL",
      },
      {
        id: 84,
        text: "Which country has won the most FIFA World Cups (men's)?",
        options: ["Germany", "Italy", "Brazil", "Argentina"],
        correctAnswer: "Brazil",
      },
      {
        id: 85,
        text: "Which hyperparameter controls the complexity in a decision tree?",
        options: ["Learning rate", "Number of estimators", "Max depth", "Random state"],
        correctAnswer: "Max depth",
      },
      {
        id: 86,
        text: "Which AI field deals with “speech to text” and “text to speech”?",
        options: [
          "Computer Vision",
          "Knowledge Representation",
          "Natural Language Processing",
          "Fuzzy Logic",
        ],
        correctAnswer: "Natural Language Processing",
      },
      {
        id: 87,
        text: "Who invented the World Wide Web?",
        options: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"],
        correctAnswer: "Tim Berners-Lee",
      },
      {
        id: 88,
        text: "What is the primary goal of the OSI model?",
        options: [
          "Provide internet access to all users",
          "Speed up network communication",
          "Standardize networking protocols for interoperability",
          "Replace TCP/IP model",
        ],
        correctAnswer: "Standardize networking protocols for interoperability",
      },
      {
        id: 89,
        text: "What is the Central Limit Theorem?",
        options: [
          "Mean of sample equals population mean",
          "Sum of data is normally distributed",
          "Sample means approximate a normal distribution as sample size grows",
          "Sample variance becomes zero",
        ],
        correctAnswer: "Sample means approximate a normal distribution as sample size grows",
      },
      {
        id: 90,
        text: "Which African country has never been colonized?",
        options: ["Ghana", "Ethiopia", "Nigeria", "Kenya"],
        correctAnswer: "Ethiopia",
      },
      {
        id: 91,
        text: "What is the capital of Kazakhstan?",
        options: ["Almaty", "Astana", "Tashkent", "Bishkek"],
        correctAnswer: "Astana",
      },
      {
        id: 92,
        text: "What is principal aim of “unsupervised learning”?",
        options: [
          "Predicting target values",
          "Discovering hidden patterns",
          "Maximizing accuracy",
          "Guaranteeing causality",
        ],
        correctAnswer: "Discovering hidden patterns",
      },
      {
        id: 93,
        text: "In Decision Trees, “Gini Impurity” is used for:",
        options: [
          "Splitting nodes for classification",
          "Measuring feature importance",
          "Selecting regression coefficients",
          "Normalizing input values",
        ],
        correctAnswer: "Splitting nodes for classification",
      },
      {
        id: 94,
        text: "What will the following query do? `SELECT COUNT(*) FROM table WHERE column IS NULL`?",
        options: [
          "Count all rows",
          "Count rows with NULL values in the column",
          "Count non-NULL values",
          "Throw error",
        ],
        correctAnswer: "Count rows with NULL values in the column",
      },
      {
        id: 95,
        text: "Which of the following is a framework for building deep learning models?",
        options: ["Flask", "TensorFlow", "Hadoop", "Redis"],
        correctAnswer: "TensorFlow",
      },
      {
        id: 96,
        text: "Which of the following does not assume normal distribution of the data?",
        options: ["Pearson correlation", "Spearman correlation", "T-test", "ANOVA"],
        correctAnswer: "Spearman correlation",
      },
      {
        id: 97,
        text: "Which country recently launched the Chandrayaan-3 lunar mission?",
        options: ["China", "Japan", "India", "USA"],
        correctAnswer: "India",
      },
      {
        id: 98,
        text: "What is the main purpose of a virtual machine (VM)?",
        options: [
          "To back up files",
          "To run programs faster",
          "To emulate a hardware environment for running OS/software",
          "To connect remote servers",
        ],
        correctAnswer: "To emulate a hardware environment for running OS/software",
      },
      {
        id: 99,
        text: "In C/C++, which operator is used for pointer dereferencing?",
        options: ["&", "*", "->", "%"],
        correctAnswer: "*",
      },
      {
        id: 100,
        text: "Which of the following algorithms is used for both classification and regression?",
        options: ["Logistic Regression", "Decision Tree", "K-means", "Naive Bayes"],
        correctAnswer: "Decision Tree",
      },
    ],
  },
  {
    round: 3,
    name: "Round 3",
    questions: [
      {
        id: 1,
        text: "In computer networks, the protocol used for secure email transmission is:",
        options: ["SMTP", "IMAP", "POP3", "S/MIME"],
        correctAnswer: "S/MIME",
      },
      {
        id: 2,
        text: "In operating systems, the Banker’s Algorithm is used for:",
        options: [
          "CPU Scheduling",
          "Deadlock Avoidance",
          "Memory Management",
          "Disk Scheduling",
        ],
        correctAnswer: "Deadlock Avoidance",
      },
      {
        id: 3,
        text: "The “Turing Test” was proposed to evaluate a machine’s ability to:",
        options: [
          "Solve complex equations",
          "Display intelligence equivalent to humans",
          "Store large datasets",
          "Perform faster computation",
        ],
        correctAnswer: "Display intelligence equivalent to humans",
      },
      {
        id: 4,
        text: "In expert systems, the “inference engine” is responsible for:",
        options: [
          "Storing facts",
          "Drawing conclusions from rules and facts",
          "Data preprocessing",
          "Feature extraction",
        ],
        correctAnswer: "Drawing conclusions from rules and facts",
      },
      {
        id: 5,
        text: "Which is the oldest written language still in use today?",
        options: ["Sanskrit", "Hebrew", "Tamil", "Greek"],
        correctAnswer: "Tamil",
      },
      {
        id: 6,
        text: "Which search algorithm guarantees finding the optimal solution if the cost is uniform?",
        options: ["Depth-First Search", "Breadth-First Search", "Hill Climbing", "Greedy Search"],
        correctAnswer: "Breadth-First Search",
      },
      {
        id: 7,
        text: "The major drawback of heuristic search is:",
        options: [
          "Requires large memory",
          "May not guarantee optimal solution",
          "Cannot be used for games",
          "Works only for linear data",
        ],
        correctAnswer: "May not guarantee optimal solution",
      },
      {
        id: 8,
        text: "Who was the first person to calculate the circumference of the Earth?",
        options: ["Aristotle", "Pythagoras", "Eratosthenes", "Archimedes"],
        correctAnswer: "Eratosthenes",
      },
      {
        id: 9,
        text: "Which evaluation metric is most suitable for an imbalanced classification problem?",
        options: ["Accuracy", "Precision & Recall", "Mean Squared Error", "R² Score"],
        correctAnswer: "Precision & Recall",
      },
      {
        id: 10,
        text: "In clustering, the “Elbow Method” is used for:",
        options: [
          "Determining the best distance metric",
          "Finding the optimal number of clusters",
          "Reducing overfitting",
          "Handling missing values",
        ],
        correctAnswer: "Finding the optimal number of clusters",
      },
      {
        id: 11,
        text: "Which of the following problems is undecidable?",
        options: [
          "Sorting a list",
          "Halting Problem",
          "Finding shortest path in a graph",
          "Binary Search",
        ],
        correctAnswer: "Halting Problem",
      },
      {
        id: 12,
        text: "In deep learning, dropout is used to:",
        options: [
          "Increase training speed",
          "Prevent overfitting",
          "Reduce dataset size",
          "Improve gradient descent",
        ],
        correctAnswer: "Prevent overfitting",
      },
      {
        id: 13,
        text: "In AI, a “heuristic function” is used to:",
        options: [
          "Guarantee optimal solutions",
          "Estimate the cost of reaching the goal",
          "Eliminate the need for training",
          "Reduce computation to zero",
        ],
        correctAnswer: "Estimate the cost of reaching the goal",
      },
      {
        id: 14,
        text: "Which AI approach uses “membership functions” to handle uncertainty?",
        options: ["Expert Systems", "Fuzzy Logic", "Bayesian Networks", "Genetic Algorithms"],
        correctAnswer: "Fuzzy Logic",
      },
      {
        id: 15,
        text: "In Natural Language Processing, “word embeddings” like Word2Vec are used to:",
        options: [
          "Convert words into numerical vectors",
          "Compress datasets",
          "Detect grammar errors",
          "Increase dataset size",
        ],
        correctAnswer: "Convert words into numerical vectors",
      },
      {
        id: 16,
        text: "In compiler design, which phase is responsible for generating intermediate code?",
        options: [
          "Lexical Analysis",
          "Syntax Analysis",
          "Semantic Analysis",
          "Intermediate Code Generation",
        ],
        correctAnswer: "Intermediate Code Generation",
      },
      {
        id: 17,
        text: "A knowledge representation scheme that uses nodes and edges is called:",
        options: ["Decision Table", "Semantic Network", "Production Rules", "Truth Table"],
        correctAnswer: "Semantic Network",
      },
      {
        id: 18,
        text: "In relational algebra, the “JOIN” operation is equivalent to:",
        options: [
          "Cartesian Product + Selection",
          "Projection + Union",
          "Intersection + Difference",
          "Aggregation + Selection",
        ],
        correctAnswer: "Cartesian Product + Selection",
      },
      {
        id: 19,
        text: "The L1 regularization term in machine learning promotes:",
        options: [
          "Feature elimination (sparsity)",
          "Smaller but non-zero coefficients",
          "Overfitting",
          "Higher bias",
        ],
        correctAnswer: "Feature elimination (sparsity)",
      },
      {
        id: 20,
        text: "Which neural network is specifically designed for sequence data like speech and text?",
        options: ["CNN", "RNN", "GAN", "SOM"],
        correctAnswer: "RNN",
      },
      {
        id: 21,
        text: "Which is the only continent without any active volcanoes?",
        options: ["Asia", "Africa", "Australia", "Europe"],
        correctAnswer: "Australia",
      },
      {
        id: 22,
        text: "Who wrote the book Arthashastra?",
        options: ["Panini", "Kalidasa", "Chanakya (Kautilya)", "Patanjali"],
        correctAnswer: "Chanakya (Kautilya)",
      },
      {
        id: 23,
        text: "Who was the first astronaut to perform a spacewalk?",
        options: ["Yuri Gagarin", "Alexei Leonov", "Neil Armstrong", "John Glenn"],
        correctAnswer: "Alexei Leonov",
      },
      {
        id: 24,
        text: "Which activation function helps solve the vanishing gradient problem in deep learning?",
        options: ["Sigmoid", "Tanh", "ReLU", "Softmax"],
        correctAnswer: "ReLU",
      },
      {
        id: 25,
        text: "In cryptography, RSA security is based on the difficulty of:",
        options: [
          "Discrete logarithm problem",
          "Integer factorization problem",
          "Matrix inversion problem",
          "Hash collision problem",
        ],
        correctAnswer: "Integer factorization problem",
      },
      {
        id: 26,
        text: "Which of the following is not a type of cache mapping technique?",
        options: [
          "Direct Mapping",
          "Associative Mapping",
          "Set-Associative Mapping",
          "Recursive Mapping",
        ],
        correctAnswer: "Recursive Mapping",
      },
      {
        id: 27,
        text: "Which of the following is a non-parametric algorithm?",
        options: ["Linear Regression", "K-Nearest Neighbors (KNN)", "Logistic Regression", "Naïve Bayes"],
        correctAnswer: "K-Nearest Neighbors (KNN)",
      },
      {
        id: 28,
        text: "In databases, the highest level of isolation in transactions is:",
        options: [
          "Read Uncommitted",
          "Read Committed",
          "Repeatable Read",
          "Serializable",
        ],
        correctAnswer: "Serializable",
      },
      {
        id: 29,
        text: "Who was the first woman to win a Nobel Prize?",
        options: ["Dorothy Hodgkin", "Marie Curie", "Rosalind Franklin", "Lise Meitner"],
        correctAnswer: "Marie Curie",
      },
      {
        id: 30,
        text: "The book Origin of Species was written by:",
        options: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "James Watson"],
        correctAnswer: "Charles Darwin",
      },
      {
        id: 31,
        text: "In Random Forest, each tree is trained on:",
        options: [
          "The full dataset",
          "A bootstrap sample of the dataset",
          "Only outliers in the dataset",
          "A single feature of the dataset",
        ],
        correctAnswer: "A bootstrap sample of the dataset",
      },
      {
        id: 32,
        text: "Which metal has the highest melting point?",
        options: ["Iron", "Tungsten", "Platinum", "Titanium"],
        correctAnswer: "Tungsten",
      },
      {
        id: 33,
        text: "The river Nile flows into which sea?",
        options: ["Red Sea", "Mediterranean Sea", "Arabian Sea", "Black Sea"],
        correctAnswer: "Mediterranean Sea",
      },
      {
        id: 34,
        text: "The perceptron learning algorithm can only classify:",
        options: [
          "Non-linear data",
          "Linearly separable data",
          "Multi-class data",
          "Temporal sequences",
        ],
        correctAnswer: "Linearly separable data",
      },
      {
        id: 35,
        text: "Which layer of the OSI model deals with encryption and compression?",
        options: ["Transport Layer", "Session Layer", "Presentation Layer", "Application Layer"],
        correctAnswer: "Presentation Layer",
      },
      {
        id: 36,
        text: "The first artificial satellite, Sputnik 1, was launched by which country?",
        options: ["USA", "USSR (Soviet Union)", "Germany", "China"],
        correctAnswer: "USSR (Soviet Union)",
      },
      {
        id: 37,
        text: "The AI term “Singularity” refers to:",
        options: [
          "A point where AI surpasses human intelligence",
          "A failure in neural networks",
          "Collapse of search algorithms",
          "Limitation of reinforcement learning",
        ],
        correctAnswer: "A point where AI surpasses human intelligence",
      },
      {
        id: 38,
        text: "In Machine Learning, the “curse of dimensionality” mainly affects:",
        options: [
          "Training speed only",
          "Model interpretability only",
          "Distance-based algorithms like KNN",
          "Linear regression only",
        ],
        correctAnswer: "Distance-based algorithms like KNN",
      },
      {
        id: 39,
        text: "In Operating Systems, “thrashing” is caused by:",
        options: ["High CPU utilization", "High paging activity", "Deadlock", "Poor scheduling"],
        correctAnswer: "High paging activity",
      },
      {
        id: 40,
        text: "The attention mechanism in AI was first introduced for which task?",
        options: [
          "Image Classification",
          "Neural Machine Translation",
          "Speech Recognition",
          "Reinforcement Learning",
        ],
        correctAnswer: "Neural Machine Translation",
      },
      {
        id: 41,
        text: "Which algorithm is used by Google’s AlphaGo to defeat human Go players?",
        options: [
          "A* Search",
          "Minimax with Alpha-Beta",
          "Deep Reinforcement Learning",
          "Expectation Maximization",
        ],
        correctAnswer: "Deep Reinforcement Learning",
      },
      {
        id: 42,
        text: "What is the key difference between model-based and model-free reinforcement learning?",
        options: [
          "Model-based uses environment dynamics, model-free does not",
          "Model-free is always faster",
          "Model-based cannot use rewards",
          "Model-free works only with supervised data",
        ],
        correctAnswer: "Model-based uses environment dynamics, model-free does not",
      },
      {
        id: 43,
        text: "GANs (Generative Adversarial Networks) consist of:",
        options: ["Encoder + Decoder", "Generator + Discriminator", "Actor + Critic", "Teacher + Student"],
        correctAnswer: "Generator + Discriminator",
      },
      {
        id: 44,
        text: "Q-learning is a type of:",
        options: [
          "Supervised Learning",
          "Reinforcement Learning",
          "Unsupervised Learning",
          "Semi-supervised Learning",
        ],
        correctAnswer: "Reinforcement Learning",
      },
      {
        id: 45,
        text: "The Bagging technique in ensemble learning mainly reduces:",
        options: ["Bias", "Variance", "Both bias and variance equally", "Dimensionality"],
        correctAnswer: "Variance",
      },
      {
        id: 46,
        text: "The “frame problem” in AI is related to:",
        options: [
          "Difficulty in representing dynamic changes in the world",
          "Inability to recognize images",
          "Storing large datasets",
          "Speed of neural networks",
        ],
        correctAnswer: "Difficulty in representing dynamic changes in the world",
      },
      {
        id: 47,
        text: "Which algorithm is used for machine translation in modern NLP systems?",
        options: ["Hidden Markov Model", "Transformer", "Naïve Bayes", "Decision Tree"],
        correctAnswer: "Transformer",
      },
      {
        id: 48,
        text: "In robotics, SLAM stands for:",
        options: [
          "Sequential Logic and Motion",
          "Simultaneous Localization and Mapping",
          "Smart Learning and Modeling",
          "Spatial Learning and Movement",
        ],
        correctAnswer: "Simultaneous Localization and Mapping",
      },
      {
        id: 49,
        text: "Gradient Descent can sometimes get stuck in:",
        options: ["Outliers", "Overfitting", "Local minima", "High variance"],
        correctAnswer: "Local minima",
      },
      {
        id: 50,
        text: "Describe the function of an activation layer in neural networks:",
        options: ["Reduces model size", "Compiles the model", "Stores weights", "Introduces nonlinearity for complex functions"],
        correctAnswer: "Introduces nonlinearity for complex functions",
      },
    ],
  },
  // This is the complete object for the Winner Round.
// Replace the existing Winner Round object in your questions.js file with this.
  {
    round: 4,
    name: "Winner Round",
    questions: [
      {
        id: 1,
        text: "Which of the following is NOT part of the ACID properties in databases?",
        options: ["Atomicity", "Isolation", "Durability", "Distribution"],
        correctAnswer: "Distribution",
      },
      {
        id: 2,
        text: "Which of the following describes Weak AI?",
        options: [
          "Human-level intelligence",
          "AI that is task-specific",
          "Conscious AI",
          "AI capable of general reasoning",
        ],
        correctAnswer: "AI that is task-specific",
      },
      {
        id: 3,
        text: "In distributed databases, “eventual consistency” is an example of:",
        options: [
          "Strong consistency",
          "Weak consistency",
          "Serializability",
          "Two-phase commit",
        ],
        correctAnswer: "Weak consistency",
      },
      {
        id: 4,
        text: "Which logic is used for reasoning about time and events in AI?",
        options: ["Propositional Logic", "Temporal Logic", "Modal Logic", "Fuzzy Logic"],
        correctAnswer: "Temporal Logic",
      },
      {
        id: 5,
        text: "What is the difference between bagging and boosting?",
        options: [
          "Bagging reduces bias; boosting reduces variance",
          "Bagging reduces variance; boosting reduces bias",
          "Both reduce bias",
          "Both reduce variance",
        ],
        correctAnswer: "Bagging reduces variance; boosting reduces bias",
      },
      {
        id: 6,
        text: "Which technique is commonly used to reduce the dimensionality of a dataset while preserving variance?",
        options: ["PCA", "k-Means", "t-SNE", "Bagging"],
        correctAnswer: "PCA",
      },
      {
        id: 7,
        text: "Which of the following is true for asymmetric encryption?",
        options: [
          "Uses the same key for encryption and decryption",
          "Uses two separate keys (public and private)",
          "Cannot be used for digital signatures",
          "Is faster than symmetric encryption for large data",
        ],
        correctAnswer: "Uses two separate keys (public and private)",
      },
      {
        id: 8,
        text: "Which heuristic search technique uses a probability-based method to escape local optima?",
        options: ["Hill Climbing", "Beam Search", "Simulated Annealing", "A* Search"],
        correctAnswer: "Simulated Annealing",
      },
      {
        id: 9,
        text: "In the TCP/IP model, which protocol ensures reliable data transmission?",
        options: ["UDP", "IP", "TCP", "ICMP"],
        correctAnswer: "TCP",
      },
      {
        id: 10,
        text: "Which probabilistic graphical model allows both directed and undirected dependencies?",
        options: ["Bayesian Network", "Hidden Markov Model", "Conditional Random Field", "Chain Graph"],
        correctAnswer: "Chain Graph",
      },
      {
        id: 11,
        text: "In hypothesis testing, what does a p-value represent?",
        options: [
          "Probability that null hypothesis is true",
          "Probability of observing the data given that null hypothesis is true",
          "Type II error probability",
          "The effect size",
        ],
        correctAnswer: "Probability of observing the data given that null hypothesis is true",
      },
      {
        id: 12,
        text: "Which search algorithm uses both the cost to reach the node and the estimated cost to the goal?",
        options: ["BFS", "DFS", "A* Search", "Greedy Best-First Search"],
        correctAnswer: "A* Search",
      },
      {
        id: 13,
        text: "In TCP, what mechanism ensures in-order delivery of packets?",
        options: [
          "Sliding window with sequence numbers",
          "Three-way handshake",
          "TTL decrementing",
          "Checksum verification",
        ],
        correctAnswer: "Sliding window with sequence numbers",
      },
      {
        id: 14,
        text: "Which algorithm is most suitable for detecting anomalies in high-dimensional data?",
        options: [
          "Linear Regression",
          "Isolation Forest",
          "k-Means",
          "PCA without transformation",
        ],
        correctAnswer: "Isolation Forest",
      },
      {
        id: 15,
        text: "Which of the following methods is used to handle multicollinearity in regression?",
        options: [
          "Increase the sample size",
          "Use Ridge Regression",
          "Use logistic regression instead",
          "Reduce the number of observations",
        ],
        correctAnswer: "Use Ridge Regression",
      },
      {
        id: 16,
        text: "In k-Means clustering, the objective function aims to minimize:",
        options: [
          "Between-cluster variance",
          "Within-cluster sum of squares",
          "Silhouette score",
          "Manhattan distance",
        ],
        correctAnswer: "Within-cluster sum of squares",
      },
      {
        id: 17,
        text: "What is the main advantage of using Convolutional Neural Networks (CNNs) for image processing?",
        options: [
          "Works without backpropagation",
          "Reduces the number of parameters using weight sharing",
          "Does not require activation functions",
          "Eliminates the need for large datasets",
        ],
        correctAnswer: "Reduces the number of parameters using weight sharing",
      },
      {
        id: 18,
        text: "Which memory allocation strategy may lead to external fragmentation?",
        options: [
          "Paging",
          "Segmentation with variable partitioning",
          "Buddy System",
          "Slab Allocation",
        ],
        correctAnswer: "Segmentation with variable partitioning",
      },
      {
        id: 19,
        text: "Which of these is a key limitation of Generative Adversarial Networks (GANs)?",
        options: [
          "They cannot generate high-resolution images",
          "They suffer from mode collapse where diversity in outputs is lost",
          "They cannot learn from unlabelled data",
          "They do not use backpropagation",
        ],
        correctAnswer: "They suffer from mode collapse where diversity in outputs is lost",
      },
      {
        id: 20,
        text: "In deep learning, what does the term “vanishing gradient” refer to?",
        options: [
          "Gradient values become very large during backpropagation",
          "Gradient values become very small, slowing or stopping learning",
          "Weights are initialized to zero",
          "Dropout removes too many neurons",
        ],
        correctAnswer: "Gradient values become very small, slowing or stopping learning",
      },
      {
        id: 21,
        text: "Which of the following distributions is used in Logistic Regression to model probabilities?",
        options: [
          "Normal Distribution",
          "Poisson Distribution",
          "Bernoulli Distribution",
          "Exponential Distribution",
        ],
        correctAnswer: "Bernoulli Distribution",
      },
      {
        id: 22,
        text: "Which network protocol uses “slow start” to prevent congestion?",
        options: ["UDP", "TCP", "ICMP", "BGP"],
        correctAnswer: "TCP",
      },
      {
        id: 23,
        text: "In Neural Networks, what is the role of the activation function?",
        options: [
          "Initialize weights",
          "Introduce non-linearity",
          "Reduce overfitting",
          "Normalize input features",
        ],
        correctAnswer: "Introduce non-linearity",
      },
      {
        id: 24,
        text: "Which of the following is an uninformed search strategy?",
        options: ["A* Search", "Greedy Search", "Uniform Cost Search", "Alpha-Beta Pruning"],
        correctAnswer: "Uniform Cost Search",
      },
      {
        id: 25,
        text: "Which metric is most appropriate for evaluating an imbalanced binary classification model?",
        options: ["Accuracy", "Precision", "F1-Score", "Mean Absolute Error"],
        correctAnswer: "F1-Score",
      },
      {
        id: 26,
        text: "Which graph algorithm uses a priority queue to always expand the node with the lowest cumulative cost?",
        options: ["DFS", "BFS", "Dijkstra’s algorithm", "Bellman-Ford"],
        correctAnswer: "Dijkstra’s algorithm",
      },
      {
        id: 27,
        text: "What is the purpose of Garbage Collection in programming languages like Java?",
        options: [
          "To improve CPU performance",
          "To automatically reclaim unused memory",
          "To delete disk files",
          "To optimize network communication",
        ],
        correctAnswer: "To automatically reclaim unused memory",
      },
      {
        id: 28,
        text: "Which of the following methods is used to handle the “exploration vs exploitation” trade-off in Reinforcement Learning?",
        options: [
          "Gradient Descent",
          "ε-greedy strategy",
          "Principal Component Analysis",
          "Backpropagation",
        ],
        correctAnswer: "ε-greedy strategy",
      },
      {
        id: 29,
        text: "What is the main disadvantage of using a very high number of principal components in PCA?",
        options: [
          "Increased overfitting",
          "Decreased explained variance",
          "Increased interpretability",
          "Reduced dimensionality",
        ],
        correctAnswer: "Increased overfitting",
      },
      {
        id: 30,
        text: "Which of the following is NOT a characteristic of an intelligent agent?",
        options: ["Autonomy", "Reactivity", "Proactiveness", "Ignoring environment feedback"],
        correctAnswer: "Ignoring environment feedback",
      },
    ],
  },
];